ignore_repositories = ["kengo-k.github.io", "study-laravel"]
ignore_languages = ["HTML", "PHP", "Blade", "Vue", "CSS", "Sass", "Makefile", "Batchfile", "Shell", "SCSS", "Dockerfile", "Vim Script"]
languages_count = 10
