languages_count = 10
ignore_repositories = ["kengo-k.github.io", "kengo-k"]
ignore_languages = ["PHP", "Blade", "Batchfile", "Vue", "Dockerfile", "Makefile", "HTML", "Vim Script"]

[language_mapping]
SCSS = "CSS"

[rename_language]
CSS = "CSS/SCSS"
