name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Run
        run: ./target/release/github-summary
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRETS_KEY }}
      - name: Checkout Profile repository
        uses: actions/checkout@v2
        with:
          repository: kengo-k/kengo-k
          token: ${{ secrets.DEPLOY_SECRETS_KEY }}
          path: dist
      - name: Copy image.svg to Profile repository
        run: cp ./target/image.svg ./dist/image.svg
      - name: Commit and push to Profile repository
        run: |
          cd ./dist
          git config --local user.email "31839234+kengo-k@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add image.svg
          git commit --amend --no-edit
          git push origin main --force
